#!/bin/bash

# game
# A simple guessing game
# Author: mcknz

# Get a random number < 100
target=$(($RANDOM % 100))

# Initialize the user's guessing
guess=

until [[ $guess -eq $target ]]; do
    read -p "Take a guess: " guess
    if [[ $guess -lt $target ]]; then
        echo "Higher!"
    elif [[ $guess -gt $target ]]; then
        echo "Lower!"
    else
        echo "You found it!"
    fi
done

echo "End of code reached"
exit 0