#!/bin/bash
# use -x option to debug all
# use "set -x" to turn on in place, and set +x to turn off.

# Simple note-taking script
# Author: mcknz

# special variable $1 takes first argument
# special variable $* takes all arguments
# echo $1 >> notes.txt
# echo $* >> notes.txt

#always good practice to quote user variables,
#   to protect against spaces and other issues.
#   double-quotes escape all variables
#double-quotes leave the value of the variable intact

# get the date
# added date via command substitution in $date variable
date=$(date)

#get the topic
topic="$1"

#filename to write to
filename="/c/src/bash-shell-scripting/module-3-variables/${topic}notes.txt"

#Ask user for input
read -p "Your note: " note


# appending note variable to the correct txt file
# $filename is quoted to allow bash to resolve a string containing a space
echo "$date: $note" >> "$filename"
echo "Note '$note' saved in $filename"