#!/bin/bash

# game
# A simple guessing game, using integer variables
# Author: mcknz

# Get a random number < 100, set as read-only integer
declare -ir target=$(( ($RANDOM % 100) + 1 ))

# Initialize the user's guessing
declare -i guess=0

until (( guess == target )); do
    read -p "Take a guess (1 to 100): " guess
    
    #if guess is 0, it is not a number
    (( guess )) || continue
    
    if (( guess < target )); then
        echo "Higher!"
    elif (( guess > target )); then
        echo "Lower!"
    else
        echo "You found it!"
    fi
done

echo "End of code reached"
exit 0