#!/bin/bash

# Demonstrates read capabilities in a loop
# Author: mcknz

echo -n "Are you sure (Y/N)? "

answered=
while [[ ! $answered ]]; do
    # -n option takes in a single key
    read -r -n 1 -s answer
    if [[ $answer = [Yy] ]]; then
        answered="yes"
    elif [[ $answer = [Nn] ]]; then
        answered="no"
    fi
done

printf "\n%s\n" $answered
